### ISSUE TITLE
Config Error:  message: "unknown field `delay_type`, expected `threads` or `extra_hash_function`", key: ["miner", "workers"] } }

### ISSUE THREAD

**Issue by tarvos21** [nervosnetwork/docs-new#117]
I downloaded the lastest ckb binaries from here: https://github.com/nervosnetwork/ckb/releases

When I try to run `ckb minier`, the command line throws an error:
```
Config Error: Error { inner: ErrorInner { kind: Custom, line: Some(36), col: 0, at: Some(864), message: "unknown field `delay_type`, expected `threads` or `extra_hash_function`", key: ["miner", "workers"] } }
```

It seems like the new binary does not understand the configuration field of `delay_type` in `miner.workers` seciton.

**Comment by tarvos21** [comment]
I downloaded the lastest ckb binaries from here :https://github.com/nervosnetwork/ckb/releases

When I try to run `ckb minier`, the command line throws an error:
```
Config Error: Error { inner: ErrorInner { kind: Custom, line: Some(36), col: 0, at: Some(864), message: "unknown field `delay_type`, expected `threads` or `extra_hash_function`", key: ["miner", "workers"] } }
```

It seems like the new binary does not understand the configuration field of `delay_type` in `miner.workers` seciton.

**Comment by doitian** [comment]
`delay_type` is only available for Dummy PoW. Comment out when you change `worker_type` to `EaglesoneSimple`.
